creation_rules:
  # All YAML files encrypted with devkey
  # devkey: daily operations (passphrase-protected)
  - path_regex: \.yaml$
    age: age1kh5p7nrcynfngjaefpryq72k5fx9cts9xtaxzda403nlr2yma9asz6mj2t
