---
# Redis Role - Main Tasks

- name: Install Redis
  include_tasks: install.yml
  tags: [install]

- name: Configure Redis
  include_tasks: configure.yml
  tags: [configure]

- name: Configure Redis persistence
  include_tasks: persistence.yml
  when: redis_persistence_enabled | default(true)
  tags: [persistence]

- name: Display Redis status
  debug:
    msg:
      - "Redis {{ redis_version }} installed successfully"
      - "Listen address: {{ redis_bind_address }}"
      - "Port: {{ redis_port }}"
      - "Max memory: {{ redis_maxmemory }}"
      - "Persistence: {{ 'enabled' if redis_persistence_enabled else 'disabled' }}"
