# AdGuard Home Configuration for OpenWRT
# File: /etc/adguardhome.yaml
# Web UI: http://192.168.20.1:3000

bind_host: 0.0.0.0
bind_port: 3000

# Admin user - change password after first login
users:
  - name: admin
    password: $2a$10$CHANGE_THIS_HASH_AFTER_INSTALL

# HTTP configuration
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:80
  session_ttl: 720h

# DNS configuration
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53

  # Statistics and query log
  statistics_interval: 24h
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 24h
  querylog_size_memory: 1000

  # Anonymize client IPs in logs
  anonymize_client_ip: false

  # Protection settings
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10

  # Parental control
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com

  # Rate limiting
  ratelimit: 20
  ratelimit_whitelist: []

  # Refuse ANY requests
  refuse_any: true

  # Upstream DNS servers (encrypted)
  upstream_dns:
    - https://dns.cloudflare.com/dns-query
    - https://dns.quad9.net/dns-query
    - tls://1.1.1.1
    - tls://9.9.9.9
    - https://doh.opendns.com/dns-query

  # Upstream DNS servers for specific domains
  upstream_dns_file: ""

  # Bootstrap DNS servers (plain DNS for resolving DoH/DoT servers)
  bootstrap_dns:
    - 1.1.1.1
    - 9.9.9.9
    - 8.8.8.8

  # Fallback DNS servers
  fallback_dns:
    - 1.1.1.1
    - 8.8.8.8

  # All DNS servers (for parallel queries)
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s

  # Access lists
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind

  # Trusted proxies
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128

  # Cache settings
  cache_size: 10000000
  cache_ttl_min: 300
  cache_ttl_max: 86400
  cache_optimistic: true

  # DNSSEC
  enable_dnssec: true

  # EDNS Client Subnet
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false

  # Maximum number of concurrent queries
  max_goroutines: 300

  # Handle PTR requests for local addresses
  local_ptr_upstreams:
    - 192.168.10.1

  # Use private reverse DNS resolvers
  use_private_ptr_resolvers: true

  # Resolve clients' IP addresses
  resolve_clients: true

  # Local domain name
  local_domain_name: lan

  # Serve plain DNS on additional IPs
  upstream_mode: load_balance

# TLS configuration (for DNS-over-TLS and DNS-over-HTTPS)
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""

# Filtering configuration
filtering:
  protection_enabled: true
  filtering_enabled: true

  # Blocklists - comprehensive protection
  filters_update_interval: 24

  filters:
    # AdGuard DNS filter
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
      name: "AdGuard DNS filter"
      id: 1

    # AdAway Default Blocklist
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
      name: "AdAway Default Blocklist"
      id: 2

    # OISD Big List
    - enabled: true
      url: https://big.oisd.nl/
      name: "OISD Blocklist Big"
      id: 3

    # HaGeZi Pro Blocklist
    - enabled: true
      url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
      name: "HaGeZi Pro Blocklist"
      id: 4

    # Malware & Phishing
    - enabled: true
      url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt
      name: "Malware & Phishing"
      id: 5

    # Tracking & Telemetry
    - enabled: true
      url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      name: "WindowsSpyBlocker"
      id: 6

  # Whitelist
  whitelist_filters: []

  # Custom filtering rules
  user_rules:
    - "@@||example.com^$important"

  # Safe browsing and parental control
  safe_browsing_enabled: false
  parental_enabled: false

  # Safe search enforcement
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true

# DHCP server configuration (disabled, using dnsmasq)
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false

# Clients configuration
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true

  persistent: []

# Log configuration
log:
  file: "/var/log/adguardhome.log"
  max_backups: 3
  max_size: 10
  max_age: 7
  compress: true
  local_time: true
  verbose: false

# OS configuration
os:
  group: ""
  user: ""
  rlimit_nofile: 0

# Schema version
schema_version: 20
