# Proxmox VE 9 Auto-Install Configuration
# Dell XPS L701X - Unattended Installation
# Documentation: https://pve.proxmox.com/wiki/Automated_Installation

[global]
# Keyboard layout
keyboard = "en-us"

# Country for timezone
country = "us"

# Timezone
timezone = "UTC"

# Root password (CHANGE THIS!)
# Generate: openssl passwd -6 "YourPassword"
root_password = "$6$rounds=656000$YourSaltHere$YourHashHere"

# Email for notifications
mailto = "admin@home.local"

# Fully Qualified Domain Name
fqdn = "gamayun.home.local"

# ============================================================
# Disk Configuration
# ============================================================

[disk-setup]
# Filesystem type
filesystem = "ext4"

# Disk selection
# Use 'first' to automatically select first disk
# Or specify exact disk: '/dev/sda'
disk_list = ["first"]

# Disk filtering: 'any' or 'all'
filter_match = "any"

# LVM configuration
[disk-setup.lvm]
# hdsize: Size for root filesystem in GB (leave rest for LVM thin pool)
# swapsize: Swap size in GB (0 to disable, 2-8 recommended)
# maxroot: Maximum root filesystem size in GB
# minfree: Minimum free space to leave in LVM pool in GB
hdsize = 50      # 50 GB for root (on SSD 180GB)
swapsize = 2     # 2 GB swap
maxroot = 50     # Max 50 GB for root
minfree = 10     # Leave 10 GB free in LVM

# ZFS options (if using ZFS instead of ext4)
# [disk-setup.zfs]
# zfs_opts = "compress=on"
# pool_name = "rpool"

# ============================================================
# Network Configuration
# ============================================================

[network]
# Network source: 'from-dhcp' or 'from-answer'
# from-dhcp: Use DHCP to get IP address
# from-answer: Use static IP configuration below
source = "from-dhcp"

# Static IP configuration (only used if source = "from-answer")
# cidr = "192.168.1.100/24"
# gateway = "192.168.1.1"
# dns = "1.1.1.1"

# Interface filter (optional, to select specific interface)
# filter = "enp0s31f6"

# ============================================================
# Notes
# ============================================================

# This configuration will:
# 1. Install Proxmox VE 9 on Dell XPS L701X
# 2. Hostname: gamayun.home.local
# 3. Use ext4 filesystem on SSD (first disk)
# 4. Create 50 GB root + 2 GB swap + ~128 GB LVM thin pool
# 5. Configure network via DHCP initially
#
# After installation:
# 1. SSH to Proxmox host: ssh root@gamayun.home.local (or IP)
# 2. Run post-install scripts from /root/post-install/:
#    - 01-install-terraform.sh
#    - 02-install-ansible.sh
#    - 03-configure-storage.sh
#    - 04-configure-network.sh
#    - 05-init-git-repo.sh
# 3. Apply Ansible configuration
# 4. Apply Terraform infrastructure

# ============================================================
# Security Notes
# ============================================================

# IMPORTANT: Change root_password hash before using!
#
# Generate password hash:
#   openssl passwd -6 "YourStrongPassword"
#
# Or use mkpasswd (if available):
#   mkpasswd -m sha-512 "YourStrongPassword"
#
# Default password in this file: Homelab2025!
# Hash generated with: openssl passwd -6 "Homelab2025!"

# For production:
# 1. Generate new password hash
# 2. Update root_password field above
# 3. Keep this file secure (DO NOT commit to Git!)
