# Proxmox VE 9 - Automated Installation Answer File
# Format: TOML (required by Proxmox)
# Target: Dell XPS L701X

[global]
# Keyboard layout
keyboard = "en-us"

# Country (EE for Estonia, RU for Russia)
country = "ee"

# Timezone
timezone = "Europe/Tallinn"

# Full qualified domain name
fqdn = "proxmox.home.lan"

# Email for system notifications
mailto = "admin@home.lan"

# Root password (plain text - will be hashed during installation)
root_password = "Homelab2025!"

# For pre-hashed password instead:
# root_password_hashed = "$6$..."

[network]
# Use DHCP for network configuration
source = "from-dhcp"

# For static IP, use:
# source = "from-answer"
# cidr = "192.168.1.100/24"
# dns = "8.8.8.8"
# gateway = "192.168.1.1"

[disk-setup]
# Filesystem type
filesystem = "ext4"

# Target disk(s)
disk_list = ["sda"]

# LVM configuration
# Swap size in GB (8GB = 1x RAM)
swapsize = 8

# Root filesystem size in GB
maxroot = 30

# Minimum free space in LVM volume group
minfree = 8

# Maximum size for data volume (0 = use all remaining space)
maxvz = 0
