# Proxmox VE 9 Unattended Installation Answer File
# Target: Dell XPS L701X (Studio XPS 17)
#
# This file automates Proxmox installation with the home-lab configuration:
# - SSD 250GB (/dev/sda) for Proxmox system and fast VMs
# - HDD 500GB (/dev/sdb) will be configured post-installation
# - Built-in Ethernet for initial management (will be reconfigured)
# - USB-Ethernet will be configured post-installation

[global]
# Keyboard layout
keyboard = "en-us"

# Country/timezone settings
# Adjust these values for your location:
# - For Russia: country = "ru", timezone = "Europe/Moscow"
# - For other locations, change accordingly
country = "ee"
timezone = "EEST"

# Email for system notifications (change to your email)
mailto = "admin@home.lan"

# Root password - CHANGE THIS BEFORE USE!
# This is a placeholder - you should set a strong password
# Note: The password will be stored in plain text in this file
root_password = "Homelab2025!"

[network]
# Network source: from_dhcp or from_answer_file
# Using DHCP for initial setup, will be reconfigured post-installation
source = "from_dhcp"

# If you want static IP during installation, use:
# source = "from_answer_file"
# And uncomment these:
# hostname = "proxmox.home.lan"
# domain = "home.lan"
# address = "192.168.1.100"
# netmask = "255.255.255.0"
# gateway = "192.168.1.1"
# dns = "8.8.8.8"

# Network interface - this will be auto-detected
# The installer will use the first available interface (built-in Ethernet)
# Post-installation, we'll configure udev rules for stable naming

[disk-setup]
# Filesystem type: ext4, xfs, zfs (RAID0), zfs (RAID1), etc.
# Using ext4 for reliability and compatibility
filesystem = "ext4"

# Target disk for Proxmox installation
# IMPORTANT: This must be the SSD (/dev/sda)
# The installer will use disk selection based on:
# - disk_list = "sda" means only /dev/sda will be used
disk_list = ["sda"]

# LVM configuration for ext4
# The SSD will be partitioned as:
# - /dev/sda1: 1GB EFI partition
# - /dev/sda2: remaining space for LVM (pve VG)
#   - pve/root: root filesystem
#   - pve/swap: swap partition (8GB = 1x RAM)
#   - pve/data: thin-provisioned pool for VMs

# Swap size in GB (8GB = 1x RAM for 8GB system)
swapsize = 8

# Maximum root volume size in GB
# We'll use 30GB for root, leaving the rest for VM storage
maxroot = 30

# Minimum free space in LVM VG (in GB)
# Keep some space free for snapshots
minfree = 8

# Maximum size for lvm thin pool
# 0 means use all available space after root and swap
maxvz = 0

# Disk options
# Advanced settings (these are defaults, included for clarity)
[disk-setup.advanced]
# Use whole disk
hdsize = 0  # 0 means use entire disk

# Alignment
align = "optimal"

# For ZFS-specific options (not used with ext4)
# ashift = 12
# compress = "on"
# checksum = "on"
# copies = 1
