#!/bin/bash
# Proxmox VE 9 Post-Installation Configuration Script
# Target: Dell XPS L701X Home Lab
#
# This script configures Proxmox after unattended installation:
# - Disables enterprise repository
# - Configures network interfaces with udev rules
# - Sets up HDD storage
# - Enables optimizations (KSM, USB power management)
# - Applies home-lab network configuration
#
# Usage: Run this script after first boot via SSH
#        ssh root@<proxmox-ip>
#        bash proxmox-post-install.sh

set -e  # Exit on error

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Proxmox Post-Installation Configuration${NC}"
echo -e "${GREEN}Dell XPS L701X Home Lab${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   exit 1
fi

# Check if running on Proxmox
if [ ! -f /etc/pve/.version ]; then
    echo -e "${RED}Error: This doesn't appear to be a Proxmox system${NC}"
    exit 1
fi

# Step 1: Repository Configuration
echo -e "${BLUE}[1/8] Configuring repositories...${NC}"

# Disable enterprise repository
if [ -f /etc/apt/sources.list.d/pve-enterprise.list ]; then
    mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled
    echo "Enterprise repository disabled"
fi

# Add no-subscription repository
if [ ! -f /etc/apt/sources.list.d/pve-no-subscription.list ]; then
    echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-no-subscription.list
    echo "No-subscription repository added"
fi

# Update package lists
apt-get update

echo -e "${GREEN}✓ Repositories configured${NC}"
echo ""

# Step 2: Install essential packages
echo -e "${BLUE}[2/8] Installing essential packages...${NC}"

apt-get install -y \
    ethtool \
    lm-sensors \
    smartmontools \
    iperf3 \
    htop \
    net-tools \
    bridge-utils

echo -e "${GREEN}✓ Essential packages installed${NC}"
echo ""

# Step 3: Network Interface Detection and Configuration
echo -e "${BLUE}[3/8] Detecting network interfaces...${NC}"

# Show all interfaces
echo "Available network interfaces:"
ip link show | grep -E "^[0-9]+" | awk '{print $2}' | sed 's/:$//'
echo ""

# Detect built-in and USB Ethernet
BUILTIN_IF=$(ip link show | grep -E "en(o|p)" | head -1 | awk '{print $2}' | sed 's/:$//' || echo "")
USB_IF=$(ip link show | grep -E "enx|eth1" | head -1 | awk '{print $2}' | sed 's/:$//' || echo "")

if [ -z "$BUILTIN_IF" ]; then
    echo -e "${YELLOW}Warning: Could not auto-detect built-in Ethernet${NC}"
    echo "Please identify it manually:"
    read -p "Enter built-in Ethernet interface name: " BUILTIN_IF
fi

if [ -z "$USB_IF" ]; then
    echo -e "${YELLOW}Warning: USB-Ethernet not detected (this is normal if not connected)${NC}"
    echo "You can configure it later by re-running this script"
    USB_IF="eth-usb"  # Use target name
fi

echo "Built-in Ethernet: $BUILTIN_IF"
echo "USB-Ethernet: $USB_IF"
echo ""

# Get MAC addresses
BUILTIN_MAC=$(ip link show "$BUILTIN_IF" 2>/dev/null | grep -o 'link/ether [^ ]*' | awk '{print $2}' || echo "")
if [ -n "$USB_IF" ] && [ "$USB_IF" != "eth-usb" ]; then
    USB_MAC=$(ip link show "$USB_IF" 2>/dev/null | grep -o 'link/ether [^ ]*' | awk '{print $2}' || echo "")
else
    USB_MAC=""
fi

echo "Built-in MAC: $BUILTIN_MAC"
if [ -n "$USB_MAC" ]; then
    echo "USB MAC: $USB_MAC"
fi
echo ""

# Create udev rules for persistent naming
echo -e "${BLUE}[4/8] Creating udev rules for persistent interface names...${NC}"

cat > /etc/udev/rules.d/70-persistent-net.rules <<EOF
# Persistent network interface names for Dell XPS L701X
# Auto-generated by proxmox-post-install.sh

# Built-in Ethernet
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="$BUILTIN_MAC", NAME="eth-builtin"

EOF

if [ -n "$USB_MAC" ]; then
cat >> /etc/udev/rules.d/70-persistent-net.rules <<EOF
# USB-Ethernet adapter
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="$USB_MAC", NAME="eth-usb"
EOF
fi

echo -e "${GREEN}✓ udev rules created${NC}"
echo ""

# Step 5: Network Configuration
echo -e "${BLUE}[5/8] Configuring network bridges...${NC}"

# Backup current network config
cp /etc/network/interfaces /etc/network/interfaces.backup

# Apply home-lab network configuration
cat > /etc/network/interfaces <<'EOF'
# Proxmox Network Configuration - Dell XPS L701X Home Lab
# Auto-generated by proxmox-post-install.sh

# Loopback
auto lo
iface lo inet loopback

# Built-in Ethernet - LAN (to OpenWRT)
auto eth-builtin
iface eth-builtin inet manual

# USB-Ethernet adapter - WAN (to ISP Router)
auto eth-usb
iface eth-usb inet manual

# vmbr0 - WAN Bridge (to ISP Router via USB-Ethernet)
auto vmbr0
iface vmbr0 inet manual
    bridge-ports eth-usb
    bridge-stp off
    bridge-fd 0
    bridge-vlan-aware yes
    bridge-vids 2-4094
    comment WAN Bridge - OPNsense WAN to ISP Router

# vmbr1 - LAN Bridge (to OpenWRT WAN via built-in Ethernet)
auto vmbr1
iface vmbr1 inet manual
    bridge-ports eth-builtin
    bridge-stp off
    bridge-fd 0
    bridge-vlan-aware yes
    bridge-vids 2-4094
    comment LAN Bridge - OPNsense LAN to OpenWRT

# vmbr2 - Internal Bridge (for LXC containers)
auto vmbr2
iface vmbr2 inet static
    address 10.0.30.1/24
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    comment Internal Network - LXC containers

# vmbr99 - Management Bridge (emergency access)
auto vmbr99
iface vmbr99 inet static
    address 10.0.99.1/24
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    comment Management Network - Emergency access
EOF

echo -e "${GREEN}✓ Network configuration applied${NC}"
echo -e "${YELLOW}Note: Network changes will take effect after reboot${NC}"
echo ""

# Step 6: Storage Configuration (HDD)
echo -e "${BLUE}[6/8] Configuring HDD storage...${NC}"

# Check if HDD exists
if [ -b /dev/sdb ]; then
    echo "HDD detected: /dev/sdb"

    # Check if already partitioned
    if ! fdisk -l /dev/sdb | grep -q "^/dev/sdb1"; then
        echo "Creating partition on HDD..."
        echo -e "n\np\n1\n\n\nw" | fdisk /dev/sdb || true
        sleep 2

        echo "Creating ext4 filesystem..."
        mkfs.ext4 -F /dev/sdb1

        echo "Creating mount point..."
        mkdir -p /mnt/hdd

        echo "Adding to fstab..."
        if ! grep -q "/mnt/hdd" /etc/fstab; then
            echo "/dev/sdb1 /mnt/hdd ext4 defaults 0 2" >> /etc/fstab
        fi

        echo "Mounting HDD..."
        mount -a

        echo "Adding HDD to Proxmox storage..."
        pvesm add dir local-hdd --path /mnt/hdd --content backup,iso,vztmpl,rootdir

        echo -e "${GREEN}✓ HDD configured and added to Proxmox${NC}"
    else
        echo -e "${YELLOW}HDD already partitioned, skipping...${NC}"
    fi
else
    echo -e "${YELLOW}Warning: HDD (/dev/sdb) not detected${NC}"
    echo "You can configure it later when connected"
fi
echo ""

# Step 7: Optimizations
echo -e "${BLUE}[7/8] Applying optimizations...${NC}"

# Enable KSM (Kernel Samepage Merging) for RAM efficiency
cat > /etc/systemd/system/ksm.service <<'EOF'
[Unit]
Description=Enable Kernel Same-page Merging
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo 1 > /sys/kernel/mm/ksm/run'
ExecStart=/bin/sh -c 'echo 1000 > /sys/kernel/mm/ksm/pages_to_scan'

[Install]
WantedBy=multi-user.target
EOF

systemctl enable ksm.service
systemctl start ksm.service
echo "✓ KSM (memory deduplication) enabled"

# Disable USB autosuspend for USB-Ethernet stability
cat > /etc/rc.local <<'EOF'
#!/bin/sh -e
# Disable USB autosuspend for stability
for i in /sys/bus/usb/devices/*/power/control; do
  echo on > $i 2>/dev/null || true
done
exit 0
EOF

chmod +x /etc/rc.local
bash /etc/rc.local
echo "✓ USB autosuspend disabled"

# Configure laptop lid behavior (don't suspend when closed)
if [ -f /etc/systemd/logind.conf ]; then
    sed -i 's/^#*HandleLidSwitch=.*/HandleLidSwitch=ignore/' /etc/systemd/logind.conf
    sed -i 's/^#*HandleLidSwitchDocked=.*/HandleLidSwitchDocked=ignore/' /etc/systemd/logind.conf
    systemctl restart systemd-logind
    echo "✓ Laptop lid behavior configured (no suspend on close)"
fi

# Setup sensors for temperature monitoring
sensors-detect --auto >/dev/null 2>&1 || true
echo "✓ Temperature sensors configured"

echo -e "${GREEN}✓ Optimizations applied${NC}"
echo ""

# Step 8: Final Summary
echo -e "${BLUE}[8/8] Configuration Summary${NC}"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Post-installation complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Configuration applied:"
echo "  ✓ Repositories configured (no-subscription)"
echo "  ✓ Network interfaces: eth-builtin, eth-usb"
echo "  ✓ Bridges: vmbr0 (WAN), vmbr1 (LAN), vmbr2 (Internal), vmbr99 (Mgmt)"
if [ -b /dev/sdb ]; then
    echo "  ✓ HDD storage configured at /mnt/hdd"
fi
echo "  ✓ KSM enabled for RAM optimization"
echo "  ✓ USB power management optimized"
echo "  ✓ Laptop lid behavior configured"
echo ""
echo -e "${YELLOW}IMPORTANT: Reboot required to apply network changes${NC}"
echo ""
echo "Next steps:"
echo "  1. Reboot: systemctl reboot"
echo "  2. Verify network: ip link show"
echo "  3. Create OPNsense VM"
echo "  4. Configure according to home-lab documentation"
echo ""
echo "Useful commands:"
echo "  - Check bridges: brctl show"
echo "  - Check storage: pvesm status"
echo "  - Check memory: free -h"
echo "  - Check KSM: cat /sys/kernel/mm/ksm/pages_sharing"
echo "  - Monitor temp: watch -n 2 sensors"
echo ""

# Ask for reboot
read -p "Reboot now? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Rebooting..."
    systemctl reboot
else
    echo "Please reboot manually when ready: systemctl reboot"
fi
