#!/usr/bin/env python3
"""Unit tests for compiler_runtime effective artifact emission."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

V5_TOOLS = Path(__file__).resolve().parents[2] / "topology-tools"
sys.path.insert(0, str(V5_TOOLS))

from compiler_runtime import emit_effective_artifact  # noqa: E402


def _diag_sink() -> tuple[list[dict[str, Any]], Any]:
    diags: list[dict[str, Any]] = []

    def add_diag(**kwargs: Any) -> None:
        diags.append(kwargs)

    return diags, add_diag


def test_emit_effective_artifact_skips_when_compile_failed(tmp_path: Path) -> None:
    diags, add_diag = _diag_sink()
    calls: list[dict[str, Any]] = []

    emit_effective_artifact(
        errors=1,
        compiled_contract_ok=True,
        enable_plugins=True,
        run_generate_stage=True,
        plugin_ctx=object(),
        execute_plugins=lambda **kwargs: calls.append(kwargs),
        artifact_owner=lambda _key: "core",
        output_json=tmp_path / "build" / "effective.json",
        effective_payload={"ok": True},
        add_diag=add_diag,
        repo_root=tmp_path,
    )

    assert calls == []
    assert diags == []
    assert not (tmp_path / "build" / "effective.json").exists()


def test_emit_effective_artifact_reports_generate_stage_skipped(tmp_path: Path) -> None:
    diags, add_diag = _diag_sink()
    calls: list[dict[str, Any]] = []
    output_json = tmp_path / "build" / "effective.json"

    emit_effective_artifact(
        errors=0,
        compiled_contract_ok=True,
        enable_plugins=True,
        run_generate_stage=False,
        plugin_ctx=object(),
        execute_plugins=lambda **kwargs: calls.append(kwargs),
        artifact_owner=lambda _key: "core",
        output_json=output_json,
        effective_payload={"ok": True},
        add_diag=add_diag,
        repo_root=tmp_path,
    )

    assert calls == []
    assert not output_json.exists()
    assert diags == [
        {
            "code": "I9001",
            "severity": "info",
            "stage": "emit",
            "message": "Compile success (generate stage skipped by stage selection).",
            "path": "build/effective.json",
            "confidence": 1.0,
        }
    ]


def test_emit_effective_artifact_core_owner_writes_json_after_generate(tmp_path: Path) -> None:
    diags, add_diag = _diag_sink()
    calls: list[dict[str, Any]] = []
    output_json = tmp_path / "build" / "effective.json"
    payload = {"ok": True, "items": [1, 2]}
    plugin_ctx = object()

    emit_effective_artifact(
        errors=0,
        compiled_contract_ok=True,
        enable_plugins=True,
        run_generate_stage=True,
        plugin_ctx=plugin_ctx,
        execute_plugins=lambda **kwargs: calls.append(kwargs),
        artifact_owner=lambda _key: "core",
        output_json=output_json,
        effective_payload=payload,
        add_diag=add_diag,
        repo_root=tmp_path,
    )

    assert calls == [{"stage": "generate", "ctx": plugin_ctx}]
    assert json.loads(output_json.read_text(encoding="utf-8")) == payload
    assert diags == [
        {
            "code": "I9001",
            "severity": "info",
            "stage": "emit",
            "message": "Compile success.",
            "path": "build/effective.json",
            "confidence": 1.0,
        }
    ]


def test_emit_effective_artifact_plugin_owner_requires_generated_output(tmp_path: Path) -> None:
    diags, add_diag = _diag_sink()
    output_json = tmp_path / "build" / "effective.json"

    emit_effective_artifact(
        errors=0,
        compiled_contract_ok=True,
        enable_plugins=False,
        run_generate_stage=True,
        plugin_ctx=None,
        execute_plugins=lambda **_kwargs: None,
        artifact_owner=lambda _key: "plugin",
        output_json=output_json,
        effective_payload={"ok": True},
        add_diag=add_diag,
        repo_root=tmp_path,
    )

    assert not output_json.exists()
    assert diags == [
        {
            "code": "E3001",
            "severity": "error",
            "stage": "emit",
            "message": "effective JSON artifact was not generated by plugins.",
            "path": "build/effective.json",
        }
    ]


def test_emit_effective_artifact_accepts_plugin_generated_output(tmp_path: Path) -> None:
    diags, add_diag = _diag_sink()
    output_json = tmp_path / "build" / "effective.json"

    def execute_plugins(**_kwargs: Any) -> None:
        output_json.parent.mkdir(parents=True, exist_ok=True)
        output_json.write_text('{"plugin": true}\n', encoding="utf-8")

    emit_effective_artifact(
        errors=0,
        compiled_contract_ok=True,
        enable_plugins=True,
        run_generate_stage=True,
        plugin_ctx=object(),
        execute_plugins=execute_plugins,
        artifact_owner=lambda _key: "plugin",
        output_json=output_json,
        effective_payload={"ok": True},
        add_diag=add_diag,
        repo_root=tmp_path,
    )

    assert json.loads(output_json.read_text(encoding="utf-8")) == {"plugin": True}
    assert diags == [
        {
            "code": "I9001",
            "severity": "info",
            "stage": "emit",
            "message": "Compile success.",
            "path": "build/effective.json",
            "confidence": 1.0,
        }
    ]
