vault_proxmox_api_token: ENC[AES256_GCM,data:Rq0u4pSR//nP2Sw=,iv:A1jTtPgqpbkHgiNTEBBU6hpLZ2mAS3vhPZXoIEtA7s4=,tag:bHPzTcQVtGG9JfrwxidobQ==,type:str]
vault_proxmox_root_password: ENC[AES256_GCM,data:Rs7VZLJjvRLfwZg=,iv:N4dPGFoqlSPyy3aMPtLOrEwKj8uzxHPN9E91AU/fzUo=,tag:1SPRPhUGlkNqbOZRqALUiw==,type:str]
vault_postgresql_superuser_password: ENC[AES256_GCM,data:366DTQUE6CfcGVw=,iv:p5nsHmtjDEAorir7OZXRFwqe+kY1/UBFq+1mgli7wOo=,tag:iNoApFeDxQ93npnjoO4/tw==,type:str]
vault_redis_password: ENC[AES256_GCM,data:6KiE2XpX3ZOW2kg=,iv:5TDD+YvMyHHXG/nktQyeBbclbErZRanFsNJTJxilM08=,tag:SdLnNgO3M1mkSyiHQufgxw==,type:str]
sops:
    age:
        - recipient: age12g2f2hnxvvaps5nw0ry766d672rct2famm6ylx336qcxcksq04rsncrzxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaGYrTmdjT2FNUFRZeTR4
            Y0EvNERCdGkvbS9BdFFEQVJKaWdlL0trd2xBCmRuaERRN2ZzUFovbDdCZnBFTElG
            ZnNNcUdTM1ovU2tCMktPWU9BdUtRR3cKLS0tIEFQN0NZNmFqQitXUllwZ3RuUmdr
            Q2g2K21nNkJrQ1FHUXBORXRXd2VQOWMK/vZmt7Sk1kBFvKwJ9K3rLkICMpjmddBq
            RTAw348ImQohKlc5KVPi89j9cCzM0PN2WRfSxT8YAh2WPQ+uSwANLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dr7jw9hxm0wve8p8ms77cecuppl9y2hhns0r6gh3z49fnkdfveaqc64mhp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzajJIeGRyNXlZSS9ibHE4
            aXhnTEwxc21ud3dWNzFQWTFjNi83aTJORkdrCkpMeXZOOWZTSjc2eExVb1VUbDZO
            L1hKQld6WCtiWGtXTk1ha2NtWlJNNTQKLS0tIEFLOEFuU2h2TVBOUFRPbW1hd2xx
            TGVkMDVDMzcwN0RQUTlUZDJ3ZEIycVkKSE5oLva5T3rIg1FPDe7z4H1UGUKr9g8T
            u3diJFEv4q6vsJD8tP9/C5WGndSUIi4ya+bw0cz0cJT430z7X1PQOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T09:51:49Z"
    mac: ENC[AES256_GCM,data:RGZcbtJnCouVBPTrJF97kLVEmzfWlR7G6PHTrqnAsesPPuA8dBlFS8fsgZ8xvnGoy3duwfH7xDiWS0d8DdAOs107LllAD07p6qKbYCnFFQBgjaINFxzO1CA9+fQ1jP1INkTGzkLhG4GRsUtPG3rR9O9EJ4gq4w6VFqC3nVnWJmc=,iv:RXXMH4r5DubiDHPqijf4I/lKz7drbaYQf/ZetD6smOk=,tag:lTDYWHenkZpYwBl3hwlE1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
