# Proxmox Repositories Configuration
# Configure Proxmox VE repositories for updates

---
# ============================================================
# Disable Enterprise Repository (requires subscription)
# ============================================================

- name: Disable Proxmox Enterprise repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com'
    line: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    state: present
    create: yes
    mode: '0644'
  when: not proxmox_use_enterprise_repo
  tags: repositories

# ============================================================
# Enable No-Subscription Repository (free)
# ============================================================

- name: Add Proxmox No-Subscription repository
  ansible.builtin.apt_repository:
    repo: "{{ proxmox_repo_no_subscription }}"
    state: "{{ 'present' if proxmox_use_no_subscription_repo else 'absent' }}"
    filename: pve-no-subscription
    update_cache: no
  tags: repositories

# ============================================================
# Disable Ceph Repository (if not using Ceph)
# ============================================================

- name: Disable Proxmox Ceph Enterprise repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent
  when: not proxmox_use_ceph_repo
  tags: repositories

# ============================================================
# Update APT cache
# ============================================================

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: repositories

# ============================================================
# Verify repository configuration
# ============================================================

- name: Check configured repositories
  ansible.builtin.command: apt-cache policy
  register: apt_policy
  changed_when: false
  tags: repositories

- name: Display repository configuration
  ansible.builtin.debug:
    msg:
      - "Repository configuration:"
      - "Enterprise repo: {{ 'enabled' if proxmox_use_enterprise_repo else 'disabled' }}"
      - "No-Subscription repo: {{ 'enabled' if proxmox_use_no_subscription_repo else 'disabled' }}"
      - "Ceph repo: {{ 'enabled' if proxmox_use_ceph_repo else 'disabled' }}"
  tags: repositories
