---
# PostgreSQL Role - Default Variables

# Version
postgresql_version: "15"

# Network
postgresql_listen_addresses: "*"
postgresql_port: 5432

# Directories
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_config_dir: "/etc/postgresql/{{ postgresql_version }}/main"

# Performance tuning (from RAM optimization)
postgresql_max_connections: 50
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "768MB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"
postgresql_wal_buffers: "16MB"

# Logging
postgresql_log_destination: "stderr"
postgresql_logging_collector: "on"
postgresql_log_directory: "log"
postgresql_log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
postgresql_log_rotation_age: "1d"
postgresql_log_rotation_size: "10MB"
postgresql_log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "

# Replication (disabled by default)
postgresql_wal_level: "replica"
postgresql_max_wal_senders: 3
postgresql_max_replication_slots: 3

# Authentication
postgresql_host_auth_method: "scram-sha-256"

# Databases to create
postgresql_databases:
  - name: homelab
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

# Users to create
postgresql_users:
  - name: app
    password: "{{ vault_postgresql_app_password }}"
    db: homelab
    priv: "ALL"

# Backup configuration
postgresql_backup_enabled: true
postgresql_backup_dir: "/var/backups/postgresql"
postgresql_backup_retention_days: 7
