---
# PostgreSQL Databases and Users

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF8') }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    state: present
  become_user: postgres
  loop: "{{ postgresql_databases }}"
  when: postgresql_databases is defined

- name: Create users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    db: "{{ item.db | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    encrypted: yes
    state: present
  become_user: postgres
  loop: "{{ postgresql_users }}"
  when: postgresql_users is defined
  no_log: yes
