---
# PostgreSQL Role - Main Tasks

- name: Install PostgreSQL
  include_tasks: install.yml
  tags: [install]

- name: Configure PostgreSQL
  include_tasks: configure.yml
  tags: [configure]

- name: Create databases and users
  include_tasks: databases.yml
  tags: [databases]

- name: Configure backups
  include_tasks: backup.yml
  when: postgresql_backup_enabled | default(true)
  tags: [backup]

- name: Display PostgreSQL status
  debug:
    msg:
      - "PostgreSQL {{ postgresql_version }} installed successfully"
      - "Listen address: {{ postgresql_listen_addresses }}"
      - "Port: {{ postgresql_port }}"
      - "Data directory: {{ postgresql_data_dir }}"
