---
# Apache Web Server Configuration

- name: Install Apache
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: present

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl
  notify: restart apache

- name: Configure Apache site for Nextcloud
  template:
    src: nextcloud-apache.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Enable Nextcloud site
  command: a2ensite nextcloud.conf
  args:
    creates: /etc/apache2/sites-enabled/nextcloud.conf
  notify: restart apache

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Ensure Apache is started and enabled
  systemd:
    name: apache2
    state: started
    enabled: yes
