---
# Nextcloud Configuration

- name: Configure trusted domains
  become_user: www-data
  command: >
    php {{ nextcloud_install_dir }}/occ config:system:set trusted_domains {{ item.0 }}
    --value={{ item.1 }}
  loop: "{{ nextcloud_trusted_domains | zip(range(nextcloud_trusted_domains | length)) | list }}"

- name: Configure Redis for caching
  become_user: www-data
  command: >
    php {{ nextcloud_install_dir }}/occ config:system:set {{ item.key }}
    --value={{ item.value }}
  loop:
    - { key: 'memcache.local', value: '\OC\Memcache\APCu' }
    - { key: 'memcache.distributed', value: '\OC\Memcache\Redis' }
    - { key: 'memcache.locking', value: '\OC\Memcache\Redis' }
    - { key: 'redis host', value: "{{ nextcloud_redis_host }}" }
    - { key: 'redis port', value: "{{ nextcloud_redis_port }}" }
    - { key: 'redis password', value: "{{ nextcloud_redis_password }}" }
  when: nextcloud_redis_enabled
  no_log: yes

- name: Configure Nextcloud settings
  become_user: www-data
  command: >
    php {{ nextcloud_install_dir }}/occ config:system:set {{ item.key }}
    --value={{ item.value }}
  loop:
    - { key: 'overwrite.cli.url', value: "http://{{ nextcloud_servername }}" }
    - { key: 'overwriteprotocol', value: "{{ nextcloud_overwrite_protocol }}" }
    - { key: 'maintenance_window_start', value: "{{ nextcloud_maintenance_window_start }}" }

- name: Set up Nextcloud cron job
  cron:
    name: "Nextcloud background jobs"
    minute: "*/5"
    user: www-data
    job: "php -f {{ nextcloud_install_dir }}/cron.php"

- name: Set background jobs mode to cron
  become_user: www-data
  command: php {{ nextcloud_install_dir }}/occ background:cron
