---
# Nextcloud Installation

- name: Check if Nextcloud is already installed
  stat:
    path: "{{ nextcloud_install_dir }}/occ"
  register: nextcloud_installed

- name: Download Nextcloud
  get_url:
    url: "{{ nextcloud_download_url }}"
    dest: /tmp/nextcloud.tar.bz2
    mode: '0644'
  when: not nextcloud_installed.stat.exists

- name: Extract Nextcloud
  unarchive:
    src: /tmp/nextcloud.tar.bz2
    dest: /var/www
    remote_src: yes
    owner: www-data
    group: www-data
  when: not nextcloud_installed.stat.exists

- name: Set Nextcloud permissions
  file:
    path: "{{ nextcloud_install_dir }}"
    owner: www-data
    group: www-data
    recurse: yes
  when: not nextcloud_installed.stat.exists

- name: Create Nextcloud database
  postgresql_db:
    name: "{{ nextcloud_db_name }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present
  delegate_to: "{{ nextcloud_db_host }}"
  become_user: postgres
  when: not nextcloud_installed.stat.exists

- name: Create Nextcloud database user
  postgresql_user:
    name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_password }}"
    db: "{{ nextcloud_db_name }}"
    priv: "ALL"
    encrypted: yes
    state: present
  delegate_to: "{{ nextcloud_db_host }}"
  become_user: postgres
  when: not nextcloud_installed.stat.exists
  no_log: yes

- name: Install Nextcloud
  become_user: www-data
  command: >
    php {{ nextcloud_install_dir }}/occ maintenance:install
    --database {{ nextcloud_db_type }}
    --database-host {{ nextcloud_db_host }}
    --database-name {{ nextcloud_db_name }}
    --database-user {{ nextcloud_db_user }}
    --database-pass {{ nextcloud_db_password }}
    --admin-user {{ nextcloud_admin_user }}
    --admin-pass {{ nextcloud_admin_password }}
    --data-dir {{ nextcloud_data_dir }}
  args:
    creates: "{{ nextcloud_config_dir }}/config.php"
  no_log: yes
