---
# PHP Installation and Configuration

- name: Install PHP and required extensions
  apt:
    name:
      - php
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-imagick
      - php-intl
      - php-mbstring
      - php-xml
      - php-zip
      - php-pgsql
      - php-redis
      - php-bcmath
      - php-gmp
      - php-apcu
    state: present

- name: Configure PHP for Nextcloud
  lineinfile:
    path: /etc/php/8.2/apache2/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^memory_limit =', line: "memory_limit = {{ nextcloud_php_memory_limit }}" }
    - { regexp: '^upload_max_filesize =', line: "upload_max_filesize = {{ nextcloud_php_upload_max_filesize }}" }
    - { regexp: '^post_max_size =', line: "post_max_size = {{ nextcloud_php_post_max_size }}" }
    - { regexp: '^max_execution_time =', line: "max_execution_time = {{ nextcloud_php_max_execution_time }}" }
  notify: restart apache

- name: Configure PHP CLI for Nextcloud
  lineinfile:
    path: /etc/php/8.2/cli/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^memory_limit =', line: "memory_limit = {{ nextcloud_php_memory_limit }}" }
