---
# Nextcloud Prerequisites

- name: Install required packages
  apt:
    name:
      - wget
      - curl
      - bzip2
      - sudo
      - libmagickcore-6.q16-6-extra
      - redis-tools
      - postgresql-client
    state: present
    update_cache: yes

- name: Create Nextcloud system user
  user:
    name: www-data
    system: yes
    shell: /usr/sbin/nologin
    home: /var/www
    create_home: no

- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0750'
  loop:
    - "{{ nextcloud_data_dir }}"
    - /var/nextcloud
