@class: class.service.web_application
@title: Service Web Application
@summary: Generic web application service role.
@version: 1.0.0

os_policy: forbidden
required_capabilities:
- cap.service.web_application.runtime
- cap.service.web_application.http
optional_capabilities: []
capability_packs: []
invariants:
- object.class_ref must equal class.id
- instance overrides must not violate class invariants
