# Proxmox VE 9 - Automated Installation Answer File
# Format: TOML (required by Proxmox)
# Target: Dell XPS L701X

[global]
# Keyboard layout
keyboard = "en-us"

# Country code (UPPERCASE! EE for Estonia, RU for Russia)
country = "EE"

# Timezone
timezone = "Europe/Tallinn"

# Full qualified domain name
fqdn = "proxmox.home.lan"

# Email for system notifications
mailto = "admin@home.lan"

# Root password (plain text - will be hashed during installation)
root_password = "Homelab2025!"

# For pre-hashed password use:
# root_password_hashed = "$6$..." (and remove root_password)

[network]
# Use DHCP for network configuration
source = "from-dhcp"

# For static IP, use:
# source = "from-answer"
# cidr = "192.168.1.100/24"
# dns = "8.8.8.8"
# gateway = "192.168.1.1"

[disk-setup]
# Filesystem type
filesystem = "ext4"

# ⚠️  DISK CONFIGURATION FOR DUAL-DISK SETUP
# ============================================
# SSD (sda): System disk - WILL BE COMPLETELY ERASED AND FORMATTED
# HDD (sdb): Data disk - PRESERVED (not touched by installer)
#
# Only specify the SSD here. The HDD will be mounted by proxmox-post-install.sh
# after installation without formatting (preserves existing data: backups, photos, etc.)
#
# Target disk(s) for SYSTEM installation (SSD only!)
disk_list = ["sda"]

# LVM configuration (для ext4 используется префикс lvm.)
# Swap size in GB (8GB = 1x RAM for Dell XPS L701X with 8GB RAM)
lvm.swapsize = 8

# Root filesystem size in GB (Proxmox OS - 20GB sufficient for base system)
lvm.maxroot = 20

# Minimum free space in LVM volume group (reserve for snapshots and overhead)
# For 180GB SSD, 4GB is reasonable
lvm.minfree = 4

# Maximum size for data volume (0 = use all remaining SSD space)
# With 180GB SSD: ~148GB available for VMs and LXC containers
# Calculation: 180 - 8 (swap) - 20 (root) - 4 (minfree) = 148GB
lvm.maxvz = 0
