---
# Common Role - Main Tasks
# Base OS configuration for all hosts

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  tags: [packages]

- name: Install essential packages
  apt:
    name: "{{ common_packages }}"
    state: present
  when: ansible_os_family == "Debian"
  tags: [packages]

- name: Configure timezone
  timezone:
    name: "{{ timezone }}"
  tags: [system]

- name: Configure locales
  locale_gen:
    name: "{{ locale }}"
    state: present
  tags: [system]

- name: Set system hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: [system]

- name: Configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'
  tags: [network]

- name: Configure DNS resolvers
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'
  tags: [network]

- name: Configure SSH daemon
  include_tasks: ssh.yml
  tags: [ssh, security]

- name: Configure firewall
  include_tasks: firewall.yml
  when: common_firewall_enabled | default(true)
  tags: [firewall, security]

- name: Configure time synchronization
  include_tasks: time.yml
  tags: [time, system]

- name: Setup log rotation
  include_tasks: logrotate.yml
  tags: [logging]

- name: Apply system tuning
  include_tasks: tuning.yml
  when: common_system_tuning | default(true)
  tags: [tuning]
