---
# SSH Configuration Tasks

- name: Configure SSH daemon
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  loop:
    - { regexp: '^#?Port ', line: "Port {{ ssh_port }}" }
    - { regexp: '^#?PermitRootLogin ', line: "PermitRootLogin {{ ssh_permit_root_login }}" }
    - { regexp: '^#?PasswordAuthentication ', line: "PasswordAuthentication {{ 'yes' if ssh_password_authentication else 'no' }}" }
    - { regexp: '^#?PubkeyAuthentication ', line: "PubkeyAuthentication {{ 'yes' if ssh_pubkey_authentication else 'no' }}" }
    - { regexp: '^#?X11Forwarding ', line: "X11Forwarding {{ 'yes' if ssh_x11_forwarding else 'no' }}" }
    - { regexp: '^#?MaxAuthTries ', line: "MaxAuthTries {{ ssh_max_auth_tries }}" }
    - { regexp: '^#?MaxSessions ', line: "MaxSessions {{ ssh_max_sessions }}" }
  notify: restart ssh

- name: Ensure SSH is enabled and started
  systemd:
    name: ssh
    enabled: yes
    state: started
