---
# Nextcloud Role - Default Variables

# Version
nextcloud_version: "28"
nextcloud_download_url: "https://download.nextcloud.com/server/releases/latest-{{ nextcloud_version }}.tar.bz2"

# Paths
nextcloud_install_dir: "/var/www/nextcloud"
nextcloud_data_dir: "/var/nextcloud/data"
nextcloud_config_dir: "{{ nextcloud_install_dir }}/config"

# Web server
nextcloud_webserver: "apache"
nextcloud_http_port: 80
nextcloud_https_port: 443
nextcloud_servername: "nextcloud.home.local"

# Admin account
nextcloud_admin_user: "admin"
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"

# Database configuration
nextcloud_db_type: "pgsql"
nextcloud_db_host: "10.0.30.10"
nextcloud_db_port: 5432
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"
nextcloud_db_password: "{{ vault_nextcloud_db_password }}"

# Redis configuration
nextcloud_redis_enabled: true
nextcloud_redis_host: "10.0.30.20"
nextcloud_redis_port: 6379
nextcloud_redis_password: "{{ vault_redis_password }}"

# PHP settings
nextcloud_php_memory_limit: "512M"
nextcloud_php_upload_max_filesize: "1024M"
nextcloud_php_post_max_size: "1024M"
nextcloud_php_max_execution_time: 3600

# Nextcloud settings
nextcloud_trusted_domains:
  - "{{ ansible_host }}"
  - "{{ nextcloud_servername }}"
  - "10.0.30.30"

nextcloud_overwrite_protocol: "http"

# Maintenance
nextcloud_maintenance_window_start: 1
nextcloud_update_checker: true
