@instance: docker-grafana
@extends: obj.docker.container.generic
@group: docker
@version: 1.1.0
source_id: docker-grafana
notes: ADR 0107 cleanup - inherits os_refs, network_ref, gateway from host
host_ref: srv-orangepi5
network:
  vlan_ref: inst.vlan.servers
  host: 210
runtime:
  image: grafana/grafana:latest
