@instance: docker-grafana
@extends: obj.docker.container.generic
@group: docker
@version: 1.0.0
source_id: docker-grafana
status: modeled
notes: ADR0087 docker workload target
host_ref: srv-orangepi5
os_refs:
- inst.os.debian.12.arm64.container_base
network:
  network_ref: inst.vlan.servers
  ip: 10.0.30.210/24
  gateway: 10.0.30.1
runtime:
  image: grafana/grafana:latest
