object: obj.service.prometheus
class_ref: class.service.monitoring
version: 1.0.0
model: Prometheus
vendor: home-lab
enabled_capabilities:
- cap.service.monitoring.runtime
- cap.service.monitoring.metrics
vendor_capabilities:
- vendor.service.prometheus.runtime
- vendor.service.prometheus.config
