#!/bin/bash
# =============================================================================
# Phase 0: Bootstrap Runbook
# =============================================================================
# This script displays day-0 bootstrap guidance before automated deployment
# Bootstrap must be completed before Terraform and Ansible phases can begin
# =============================================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                     PHASE 0: BOOTSTRAP                               ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${YELLOW}Bootstrap is the day-0 process that prepares devices for Terraform and Ansible.${NC}"
echo ""

echo -e "${GREEN}1. MikroTik Chateau LTE7 ax${NC}"
echo "   ───────────────────────────────────────────────────────────────────"
echo "   Preferred target path: Netinstall from the control node"
echo ""
echo "   a) Assemble the native execution workspace:"
echo "      cd deploy && make assemble-native"
echo ""
echo "   b) Confirm local prerequisites before reinstall:"
echo "      - netinstall-cli is installed and in PATH"
echo "      - the correct RouterOS .npk package is available locally"
echo "      - install interface, client IP, and target MAC are known"
echo "      - .work/native/bootstrap/rtr-mikrotik-chateau/init-terraform.rsc exists"
echo ""
echo "   c) Put the router into Etherboot or Netinstall mode"
echo ""
echo "   d) Run Netinstall from the control node:"
echo ""
echo "      netinstall-cli -e --mac <router-mac> -i <install-iface> -a <client-ip> \\"
echo "        -s .work/native/bootstrap/rtr-mikrotik-chateau/init-terraform.rsc \\"
echo "        /path/to/routeros-arm64.npk"
echo ""
echo "   Fallbacks if Netinstall is not available:"
echo "   e) Manual WinBox import:"
echo "      - Upload .work/native/bootstrap/rtr-mikrotik-chateau/init-terraform.rsc"
echo "      - Run: /import init-terraform.rsc"
echo ""
echo "   f) Legacy SSH-first helper for recovery only:"
echo "      python topology-tools/scripts/deployers/mikrotik_bootstrap.py --router 192.168.88.1"
echo ""
echo "   g) Verify handover before Terraform:"
echo "      curl -k -u terraform:<password> https://192.168.88.1:8443/rest/system/identity"
echo ""

echo -e "${GREEN}2. Proxmox VE (Dell XPS L701X)${NC}"
echo "   ───────────────────────────────────────────────────────────────────"
echo "   a) Create bootable USB:"
echo "      mkdir -p local/bootstrap/srv-gamayun"
echo "      cat > local/bootstrap/srv-gamayun/answer.override.toml <<'EOF'"
echo "      [global]"
echo "      root_password = \"<SHA512_PASSWORD_HASH>\""
echo "      EOF"
echo "      cd deploy && make assemble-native"
echo "      cd ../.work/native/bootstrap/srv-gamayun"
echo "      sudo ./create-uefi-autoinstall-proxmox-usb.sh /path/to/proxmox-ve.iso answer.toml /dev/sdX"
echo ""
echo "   b) Boot from USB, installation is automatic"
echo ""
echo "   c) After reboot, run post-install scripts:"
echo "      ssh root@<proxmox-ip>"
echo "      cd /root/post-install"
echo "      ./01-install-terraform.sh"
echo "      ./02-install-ansible.sh"
echo "      ./03-configure-storage.sh"
echo "      ./04-configure-network.sh"
echo ""

echo -e "${GREEN}3. Orange Pi 5${NC}"
echo "   ───────────────────────────────────────────────────────────────────"
echo "   a) Flash Armbian to NVMe with cloud-init:"
echo "      - Download Armbian for Orange Pi 5"
echo "      - Flash to NVMe using balenaEtcher"
echo "      - Use .work/native/bootstrap/srv-orangepi5/cloud-init/"
echo "      - Copy meta-data and materialized user-data to boot partition"
echo ""
echo "   b) Cloud-init handles:"
echo "      - SSH key injection"
echo "      - Hostname and baseline user creation"
echo "      - Initial bootstrap handoff for later automation"
echo ""

echo -e "${CYAN}───────────────────────────────────────────────────────────────────────${NC}"
echo ""
echo -e "${YELLOW}After completing bootstrap for all devices:${NC}"
echo ""
echo "   1. Verify connectivity:"
echo "      ping 192.168.88.1   # MikroTik"
echo "      ping 192.168.88.2   # Proxmox"
echo "      ping 192.168.88.3   # Orange Pi 5"
echo ""
echo "   2. Copy terraform.tfvars.example files and configure:"
echo "      mkdir -p local/terraform/mikrotik local/terraform/proxmox"
echo "      cp generated/terraform/mikrotik/terraform.tfvars.example local/terraform/mikrotik/terraform.tfvars"
echo "      cp generated/terraform/proxmox/terraform.tfvars.example local/terraform/proxmox/terraform.tfvars"
echo "      cd deploy && make assemble-native"
echo ""
echo "   3. Run deployment:"
echo "      cd deploy && make deploy-all"
echo ""

echo -e "${GREEN}Bootstrap checklist:${NC}"
echo "   [ ] MikroTik day-0 bootstrap completed"
echo "   [ ] MikroTik management IP and API reachable"
echo "   [ ] Proxmox installed and post-install completed"
echo "   [ ] Orange Pi 5 booted with cloud-init"
echo "   [ ] All devices reachable via SSH"
echo "   [ ] terraform.tfvars files configured"
