@instance: inst.data_asset.prometheus
@extends: obj.storage.data_asset.logs
group: data-assets
@version: 1.0.0
source_id: data-prometheus
status: mapped
notes: Prometheus TSDB
host_ref: srv-orangepi5
criticality: high
backup_policy: weekly
engine: prometheus
