# Ansible Role: Proxmox
# Proxmox VE 9 post-installation configuration for Dell XPS L701X

galaxy_info:
  author: Home Lab Administrator
  description: Proxmox VE 9 configuration for home lab infrastructure
  company: Home Lab
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bookworm  # Debian 12 (Proxmox VE 9 base)

  galaxy_tags:
    - proxmox
    - virtualization
    - homelab
    - infrastructure

dependencies: []
  # List dependencies here if needed
  # - role: common
  # - role: security
