#ENC[AES256_GCM,data:olvboXhxG2cQo3mNZKjhteeZnyXlvRY=,iv:JvoNKf2DB8XFjaqLN9bEZxbkzHtFNSgwTLUlqi/WPus=,tag:/HItoUyY8vQI6A6VUjvEdg==,type:comment]
#ENC[AES256_GCM,data:MVNESvgyJ2eKUV8pUey+QKvbOyxUYsR1LMvuUdVnlnevsYXV+KP7r9xX0yLfdQpAiqZ4gbGIlcg=,iv:koHx28VTBihYi0l+jzRRV1PTnuXiernWQrG/gaI+Tsg=,tag:Q4N0XVHRYjrJfNLen7QmQg==,type:comment]
ansible_vault_password: ENC[AES256_GCM,data:+W98aeRLBQJvowHi74wqz9kRJl8DCYOIhXOGG1HZSWagK+902NNekcLyrKc=,iv:0t6/FWs1Qn+0xB7KIozfXWkeuvhbZgha3i+gzCrcEY4=,tag:ieo35Z2jme2olBK8dVEKdg==,type:str]
sops:
    age:
        - recipient: age1kh5p7nrcynfngjaefpryq72k5fx9cts9xtaxzda403nlr2yma9asz6mj2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSU1JZlkvWXFoZmhiVWRu
            cytSOE5kZFd4N1FXaDMwWGZLVVZic1I0YkUwClNNdDNJMDQ1eW1SOXZiMUtQZkhC
            QWRUNjZQV0JrOGkyUmRFZ3o1Tmp6WFEKLS0tIDJJQU55SEpKc3ZqSURqQkVkYXVZ
            RnVDQlJza0dkZE9RaFhWTnBEYXhLVUUKt7mBJ6QLDzpPh7zyFAupxAszLLVoeIK1
            e59nfDJ7j41cIBuAcwm+3V0L0GiLLRlncKupaaVOCPLBGPEivIGu5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k69r6mhx676vmzcku86mwjhqtztdtgwum3ktke8yl3j0q4u2dazslcdv0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ1dmVVE4M1ZmUUJ1UFVn
            bzhqdWtZdnM4a1pUK1F1Z1dmbWMxZWtaUEZ3CjZkSkxzblJWei9PNEhycEwzTjlz
            MTNZRVpIQXBOUTI5NXVmSWt4Y0JLZUEKLS0tICtzc1RwSzZIRUhIZXNZR2JWYnhY
            ZEYrYTZoUUpma3ErazQzYWVGNm9hSVEKJIO9b7hMQ7pm0Jcds+ueFe06e+pMIFIN
            yKepBRGnUGmpoSXgXiJJGun7gDH1drL8j9KNPKqP+MeGrJ0UUPZnIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T12:10:24Z"
    mac: ENC[AES256_GCM,data:Y9daTOTJSQ54Y8KFWsL6k2m3LirfuBi37nslM/tTbJDisdE/ywNR1cL7v2TyaCu94A1GejeXVWUbVJIHEax5RxCWonrDDVXgAqMBTPsALuzZHIEr05RMueJ32WdybYmpMJa95zsr94pDTDUUAJseGjm2BkdAynNDI7wKP2hGbbk=,iv:uXjYlzxPtoE1TZWeAdZoxYBxLWn670BtQaDqKcmklmQ=,tag:3c6yv5qZFVk2BAtljv7PSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
