id: data-jellyfin-config
name: Jellyfin Config
type: volume
device_ref: srv-orangepi5
description: Jellyfin configuration
category: configuration
criticality: medium
backup_policy_refs:
- backup-srv-orangepi5-data
