# Ansible Inventory - Production Environment
# Home Lab Infrastructure - Dell XPS L701X

all:
  vars:
    # Global variables for all hosts
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    # Environment
    environment_name: production
    datacenter: home-lab

    # DNS servers
    dns_servers:
      - 192.168.20.1    # AdGuard Home on OpenWRT
      - 1.1.1.1         # Cloudflare (fallback)

    # NTP servers
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

  children:
    # ============================================================
    # Proxmox Hosts
    # ============================================================
    proxmox:
      hosts:
        pve-xps:
          ansible_host: 10.0.99.1
          ansible_user: root
          ansible_port: 22

          # Hardware specs
          hardware:
            model: "Dell XPS L701X"
            cpu_cores: 2
            cpu_model: "Intel Core i3-M370"
            ram_mb: 8192
            ssd_gb: 180
            hdd_gb: 500

          # Network interfaces
          network_interfaces:
            wan: eth-usb          # USB-Ethernet (via udev)
            lan: eth-builtin      # Built-in Ethernet (via udev)
            wifi: wlan0           # WiFi (optional)

          # Storage pools
          storage:
            ssd: local-lvm        # SSD for production
            hdd: local-hdd        # HDD for templates/backups
            local: local          # Local for ISOs

    # ============================================================
    # Virtual Machines
    # ============================================================
    vms:
      children:
        # OPNsense Firewall
        firewalls:
          hosts:
            opnsense-fw:
              ansible_host: 10.0.99.10
              ansible_user: root
              ansible_port: 22

              vm_id: 100
              vm_name: opnsense-firewall
              vm_cores: 2
              vm_ram_mb: 2048
              vm_disk_gb: 32
              vm_storage: local-lvm
              vm_autostart: yes
              vm_startup_order: 1

              # Network interfaces
              network:
                wan:
                  bridge: vmbr0
                  ip: dhcp           # From ISP
                lan:
                  bridge: vmbr1
                  ip: 192.168.10.1/24
                internal:
                  bridge: vmbr2
                  ip: 10.0.30.254/24
                mgmt:
                  bridge: vmbr99
                  ip: 10.0.99.10/24

              # Services
              services:
                - firewall
                - nat
                - dhcp
                - wireguard
                - nginx-proxy

    # ============================================================
    # OpenWRT Routers
    # ============================================================
    routers:
      children:
        openwrt:
          hosts:
            slate-ax:
              ansible_host: 192.168.20.1
              ansible_user: root
              ansible_port: 22
              ansible_connection: ssh

              # Device info
              device:
                model: "GL.iNet GL-AXT1800 (Slate AX)"
                firmware: "4.8.2"
                openwrt_version: "23.05"
                cpu: "MediaTek MT7621A"
                ram_mb: 512
                wifi: "WiFi 6 (802.11ax)"

              # Network configuration
              network:
                mode: home          # home or travel
                wan_ip: 192.168.10.2
                lan_ip: 192.168.20.1
                lan_network: 192.168.20.0/24
                guest_network: 192.168.30.0/24
                iot_network: 192.168.40.0/24

              # VPN servers on Slate AX
              vpn_servers:
                wireguard:
                  enabled: true
                  port: 51820
                  network: 10.0.200.0/24
                amneziawg:
                  enabled: true
                  port: 51821
                  network: 10.8.2.0/24

              # Services
              services:
                - adguard-home
                - wireguard-server
                - amneziawg-server
                - wifi-ap

    # ============================================================
    # LXC Containers
    # ============================================================
    lxc:
      vars:
        # Common LXC settings
        lxc_storage: local-lvm
        lxc_gateway: 10.0.30.254
        lxc_bridge: vmbr2
        lxc_autostart: yes

      children:
        # Database servers
        databases:
          hosts:
            postgresql:
              ansible_host: 10.0.30.10
              ansible_user: root
              ansible_port: 22

              lxc_id: 200
              lxc_name: postgresql
              lxc_cores: 2
              lxc_ram_mb: 2048
              lxc_disk_gb: 8
              lxc_template: debian-12
              lxc_startup_order: 2

              service_port: 5432

            redis:
              ansible_host: 10.0.30.20
              ansible_user: root
              ansible_port: 22

              lxc_id: 201
              lxc_name: redis
              lxc_cores: 2
              lxc_ram_mb: 1024
              lxc_disk_gb: 4
              lxc_template: debian-12
              lxc_startup_order: 2

              service_port: 6379

        # Web services
        webservices:
          hosts:
            nextcloud:
              ansible_host: 10.0.30.30
              ansible_user: root
              ansible_port: 22

              lxc_id: 202
              lxc_name: nextcloud
              lxc_cores: 2
              lxc_ram_mb: 2048
              lxc_disk_gb: 20
              lxc_template: debian-12
              lxc_startup_order: 3

              service_port: 443

            gitea:
              ansible_host: 10.0.30.40
              ansible_user: root
              ansible_port: 22

              lxc_id: 203
              lxc_name: gitea
              lxc_cores: 2
              lxc_ram_mb: 1024
              lxc_disk_gb: 8
              lxc_template: debian-12
              lxc_startup_order: 3

              service_port: 3000

        # Home automation
        homeautomation:
          hosts:
            home-assistant:
              ansible_host: 10.0.30.50
              ansible_user: root
              ansible_port: 22

              lxc_id: 204
              lxc_name: home-assistant
              lxc_cores: 2
              lxc_ram_mb: 1024
              lxc_disk_gb: 8
              lxc_template: debian-12
              lxc_startup_order: 3

              service_port: 8123

        # Monitoring
        monitoring:
          hosts:
            grafana:
              ansible_host: 10.0.30.60
              ansible_user: root
              ansible_port: 22

              lxc_id: 205
              lxc_name: grafana
              lxc_cores: 1
              lxc_ram_mb: 512
              lxc_disk_gb: 8
              lxc_template: debian-12
              lxc_startup_order: 4

              service_port: 3000

            prometheus:
              ansible_host: 10.0.30.70
              ansible_user: root
              ansible_port: 22

              lxc_id: 206
              lxc_name: prometheus
              lxc_cores: 2
              lxc_ram_mb: 1024
              lxc_disk_gb: 16
              lxc_template: debian-12
              lxc_startup_order: 4

              service_port: 9090

        # Infrastructure services
        infrastructure:
          hosts:
            nginx-proxy:
              ansible_host: 10.0.30.80
              ansible_user: root
              ansible_port: 22

              lxc_id: 207
              lxc_name: nginx-proxy
              lxc_cores: 1
              lxc_ram_mb: 512
              lxc_disk_gb: 4
              lxc_template: debian-12
              lxc_startup_order: 3

              service_port: 80

            docker-host:
              ansible_host: 10.0.30.90
              ansible_user: root
              ansible_port: 22

              lxc_id: 208
              lxc_name: docker-host
              lxc_cores: 2
              lxc_ram_mb: 2048
              lxc_disk_gb: 20
              lxc_template: debian-12
              lxc_startup_order: 3
