#!/bin/bash
# Generate cloud-init config for VPS WireGuard bootstrap
# ADR 0083: Node Initialization
#
# Usage:
#   ./scripts/bootstrap/generate-vps-cloudinit.sh [output_file]
#
# If output_file is provided, writes base64-encoded cloud-init there.
# Otherwise prints to stdout.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WG_DIR="$REPO_ROOT/generated/home-lab/wireguard"

# Check for required files
if [[ ! -f "$WG_DIR/vps-wg0.conf" ]]; then
    echo "Error: $WG_DIR/vps-wg0.conf not found" >&2
    exit 1
fi

# Base64 encode WireGuard configs
WG0_B64=$(base64 -w0 "$WG_DIR/vps-wg0.conf")
WG1_B64=""
if [[ -f "$WG_DIR/vps-wg1.conf" ]]; then
    WG1_B64=$(base64 -w0 "$WG_DIR/vps-wg1.conf")
fi

# Generate cloud-init YAML
CLOUD_INIT=$(cat <<'EOF'
#cloud-config
# Cloud-init configuration for VPS WireGuard bootstrap
# Generated by scripts/bootstrap/generate-vps-cloudinit.sh

package_update: true
package_upgrade: false

packages:
  - wireguard
  - wireguard-tools

write_files:
  - path: /etc/wireguard/wg0.conf
    owner: root:root
    permissions: '0600'
    encoding: b64
    content: WG0_PLACEHOLDER

EOF
)

# Add wg0 config
CLOUD_INIT="${CLOUD_INIT/WG0_PLACEHOLDER/$WG0_B64}"

# Add wg1 if exists
if [[ -n "$WG1_B64" ]]; then
    CLOUD_INIT+="
  - path: /etc/wireguard/wg1.conf
    owner: root:root
    permissions: '0600'
    encoding: b64
    content: $WG1_B64
"
fi

# Add runcmd section
CLOUD_INIT+='runcmd:
  # Ensure SSH is accessible first
  - systemctl enable ssh
  - systemctl start ssh
  # Make sure iptables allows SSH (in case of default DROP policy)
  - iptables -I INPUT 1 -p tcp --dport 22 -j ACCEPT
  - iptables -I INPUT 2 -m state --state ESTABLISHED,RELATED -j ACCEPT
  # Enable IP forwarding
  - sysctl -w net.ipv4.ip_forward=1
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  # Detect primary network interface (via default route)
  - PRIMARY_IF=$(ip -o route get 8.8.8.8 | sed "s/.*dev \\([^ ]*\\).*/\\1/")
  - echo "PRIMARY_IF=$PRIMARY_IF" >> /etc/environment
  # Fix wg0.conf interface name if needed
  - sed -i "s/ens3/$PRIMARY_IF/g" /etc/wireguard/wg0.conf 2>/dev/null || true
  # Enable and start wg0
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0
'

if [[ -n "$WG1_B64" ]]; then
    CLOUD_INIT+='  # Set up policy routing for Estonia chain (wg1 uses Table = 100)
  # Traffic from Estonia profile (10.100.0.6) uses routing table 100
  - ip rule add from 10.100.0.6 lookup 100 priority 100 2>/dev/null || true
  - echo "100 estonia_chain" >> /etc/iproute2/rt_tables 2>/dev/null || true
  # Enable and start wg1 (Table=100 ensures default route goes to table 100, not main)
  - systemctl enable wg-quick@wg1
  - systemctl start wg-quick@wg1
'
fi

# Output
OUTPUT_FILE="${1:-}"
CLOUD_INIT_B64=$(echo "$CLOUD_INIT" | base64 -w0)

if [[ -n "$OUTPUT_FILE" ]]; then
    echo "$CLOUD_INIT_B64" > "$OUTPUT_FILE"
    echo "Cloud-init config written to: $OUTPUT_FILE" >&2
    echo "Add to terraform.tfvars:" >&2
    echo "  cloud_init_config = \"$(cat "$OUTPUT_FILE")\"" >&2
else
    echo "$CLOUD_INIT_B64"
fi
