#!/bin/bash
# Generate Portainer admin password and store in SOPS secrets
# ADR 0072: Secrets management via SOPS/age
#
# Usage:
#   ./scripts/bootstrap/portainer-secrets.sh [--regenerate]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SECRETS_DIR="$REPO_ROOT/projects/home-lab/secrets"
SECRETS_FILE="$SECRETS_DIR/instances/srv-orangepi5.yaml"

# Check dependencies
command -v sops >/dev/null 2>&1 || { echo "ERROR: sops not found"; exit 1; }
command -v yq >/dev/null 2>&1 || { echo "ERROR: yq not found"; exit 1; }

echo "=== Portainer Admin Password Generator ==="
echo ""

# Check if file exists and is valid SOPS file
FILE_EXISTS=false
if [[ -s "$SECRETS_FILE" ]] && sops -d "$SECRETS_FILE" >/dev/null 2>&1; then
    FILE_EXISTS=true
fi

# Check if secret already exists in valid file
if $FILE_EXISTS; then
    if sops -d "$SECRETS_FILE" 2>/dev/null | yq -e '.portainer.admin_password' >/dev/null 2>&1; then
        if [[ "$1" != "--regenerate" ]]; then
            echo "Password already exists in secrets."
            echo "Use --regenerate to create a new password."
            echo ""
            echo "Current password path: portainer.admin_password"
            exit 0
        fi
        echo "Regenerating password (--regenerate specified)..."
    else
        echo "Adding Portainer password to existing secrets file..."
    fi
else
    echo "Creating new secrets file with Portainer password..."
fi

# Generate secure password (32 chars, alphanumeric)
# Using /dev/urandom for portability (avoids openssl dependency)
NEW_PASSWORD=$(head -c 256 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)

echo "Updating secrets file..."
TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT

if $FILE_EXISTS; then
    # Decrypt existing file
    sops -d "$SECRETS_FILE" > "$TEMP_FILE"
else
    # Create new file with header comment
    cat > "$TEMP_FILE" <<EOF
# srv-orangepi5 instance secrets
# Generated by portainer-secrets.sh
EOF
fi

# Add or update portainer section
yq -i ".portainer.admin_password = \"$NEW_PASSWORD\"" "$TEMP_FILE"

# Re-encrypt (use .sops.yaml from secrets directory)
# Copy temp file to secrets dir so sops finds .sops.yaml
TEMP_IN_SECRETS="$SECRETS_DIR/instances/.tmp-secrets.yaml"
cp "$TEMP_FILE" "$TEMP_IN_SECRETS"
cd "$SECRETS_DIR"
sops -e "instances/.tmp-secrets.yaml" > "$SECRETS_FILE"
rm -f "$TEMP_IN_SECRETS"
cd - >/dev/null

echo ""
echo "=== Password stored successfully ==="
echo ""
echo "Secret path: portainer.admin_password"
echo "File: $SECRETS_FILE"
echo ""
echo "To view: sops -d $SECRETS_FILE | yq '.portainer.admin_password'"
echo ""
echo "Next: Deploy password to host with portainer-setup.sh"
